config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"

  root "static_pages#home"
  get "home", to: "static_pages#home"
  namespace :admin do
    resources :books
    resources :requests, only: %i(edit update index)
    resources :categories
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
  end

  resources :account_activations, only: [:edit]
  resources :books, only: %i(show) do 
    resources :ratings do
      resources :comments
    end
    resources :user_books
  end
  resources :mark_books, only: %i(index)
  resources :users do
    resources :member do
      get :following, :followers
    end
  end
  resources :requests
  resources :search_books, only: %i(index)
  resources :my_requests, only: %i(index)
  resources :search_users, only: %i(index)
  resources :likes, only: %i(create destroy)
  resources :category_books,only: %i(index)
  resources :time_lines, only: %i(index)
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :relationships, only: [:create, :destroy]
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :category
  has_many :user_books
  has_many :requests
  has_many :ratings
  has_many :histories, as: :historyable
  mount_uploader :image, ImageUploader

  validates :name, presence: true, uniqueness: {case_sensitive: false}
  validates :description, presence: true, length: {minimum: 50}
  validates :author, presence: true
  validates :number_of_pages, presence: true, numericality: {only_integer: true}
  scope :list_book, -> {select(:id, :name, :created_at, :author, :category_id).
    includes(:category).order(created_at: :asc)}
  scope :like_by_name_author, -> (key_word){includes(:category).where("name like ? or author like ?", "%#{key_word}%", "%#{key_word}%")}
  scope :filter_book, -> (cat_id, key_word){includes(:category)
    .where("(name like ? or author like ?) and category_id = ?",
    "%#{key_word}%", "%#{key_word}%", "#{cat_id}").order(created_at: :asc)}
  scope :filter_by_category, -> (cat_id){includes(:category).where(category_id: cat_id)}
  scope :ordered, -> {order(created_at: :desc)}

  private

  def picture
    if picture.size > Settings.validate_size_image.megabytes
      errors.add :picture, (t "books.more_than")
    end
  end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  layout "admin/application"
  before_action :verify_admin, only: %i(new index add update edit destroy)
  before_action :load_book, only: %i(show update edit destroy)

  def index
    books = Book.like_by_name_author(params[:keyword])
    books = books.filter_by_category(params[:cat_id]) unless params[:cat_id].blank?
    respond_to do |format|
      format.js
      format.html {books = Book.ordered}
    end

    @books = books.ordered.page(params[:page])
      .per Settings.paginate_page
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new book_params
    if @book.save
      flash[:success] = t "books.create_success"
      redirect_to admin_books_url
    else
      flash[:error] = t "books.create_fail"
      render :new
    end
  end

  def show; end

  def update
    if @book.update_attributes book_params
      flash[:success] = t "books.update_success"
      redirect_to @book
    else
      render :edit
    end
  end

  def edit; end

  def destroy
    if @book.destroy
      flash[:success] = t "books.delete_success"
    else
      flash[:danger] = t "delete_faild"
    end
    redirect_to admin_books_url
  end

  private

  def book_params
    params.require(:book).permit :name, :description, :image,
      :author, :number_of_pages, :price, :category_id
  end

  def load_book
    @book = Book.find_by id: params[:id]
    render html: (t "not_found") if @book.nil?
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def show
    @ratings = Rating.by_book params[:id]
    @book = Book.find_by id: params[:id]
    @user_book = load_user_book.nil? ? UserBook.new : UserBook.by_book(params[:id],
                                                              current_user.id).first
    render html: (t "not_found") if @book.nil?
  end

  private

  def load_user_book
    UserBook.by_book(params[:id], current_user.id).first if logged_in?
  end
end

app/views/admin/books/_book.html.erb
<tr>
  <td><%= index_record @books.index(book), Settings.paginate_page, params[:page].to_i %></td>
  <td><%= book.name %></td>
  <td><%= book.author %></td>
  <td class="text-center"><%= book.category.title %></td>
  <td class="text-center"><%= book.created_at %></td>
  <td class="text-center">
    <%= link_to (t "books.view"), admin_book_path(book), class: "btn btn-primary btn-sm", remote: true %>
    <%= link_to (t "books.edit"), edit_admin_book_path(book), class: "btn btn-warning btn-sm" %>
    <%= link_to (t "books.delete"), admin_book_path(book), method: :delete,
      data: {confirm: (t "books.confirm")}, class: "btn btn-danger btn-sm" %>
  </td>
</tr>

app/views/admin/books/_form.html.erb
<%= form_for [:admin, @book] do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %><br>

  <%= f.label :description %>
  <%= f.text_area :description, class: "form-control" %> <br>

  <%= f.label :image %>
  <%= f.file_field :image, class: "form-control", accept: "image/jpeg,image/gif,image/png" %> <br>
  
  <div class="row">
    <div class="col-md-6">
      <%= f.label :author %>
      <%= f.text_field :author, class: "form-control" %><br>  
    </div>
    <div class="col-md-6">
      <%= f.label :number_of_pages %>
      <%= f.text_field :number_of_pages, class: "form-control" %> <br>  
    </div>
  </div>

  <%= f.label :category_id %>
  <%= f.collection_select :category_id, Category.order(:title), :id, :title,
    {prompt: true}, {class: "form-control"} %><br>
  <center>
    <%= f.submit yield(:button_text), class: "btn btn-primary btn-md" %>
  <center>
<% end %>

app/views/admin/books/_show.html.erb
<div class="modal fade" id="modalRequest" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">
          <%= t "detail_book" %>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </h5>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-md-3">
            <%= image_tag @book.image.thumb.url, class: "img-book-modal" %>
          </div>
          <div class="col-md-8">
            <h2><%= @book.author %></h2>
            <h3><%= @book.name %></h3>
            <p><%= @book.description %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/books/edit.html.erb
<% provide :button_text, (t "books.edit") %>
<center>
  <h1><%= t "layout.header.edit" %></h1>
</center>
<div class="col-md-10 col-md-offset-1">
  <div class="col-md-3">
    <%= image_tag @book.image.thumb.url, class: "img-book-modal" %>
  </div>
  <div class="col-md-9">
    <%= render "form" %>
  </div>
</div>

app/views/admin/books/index.html.erb
<center>
  <h1><%= t "books.list_book" %></h1>
</center>
<div class="col-md-10 col-md-offset-1">
  <%= form_tag admin_books_path, method: :get, id: "form_filter" do %>
    <div class="col-md-6">
      <%= text_field_tag "txt_filter_book", nil, class: "form-control txt_filter_book", placeholder: (t "type_something"), id: "txt_filter_book" %>
    </div>
    <div class="col-md-6">
      <%= select_tag "category", options_from_collection_for_select(Category.all, "id", "title", params[:category]),
        class: "form-control", include_blank: "Show all book" %>
    </div>
  <% end %>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col" class="text-center">#</th>      
        <th scope="col" class="text-center"><%= t "books.name" %></th>
        <th scope="col" class="text-center"><%= t "books.author" %></th>
        <th scope="col" class="text-center"><%= t "books.category" %></th>
        <th scope="col" class="text-center"><%= t "books.created_at" %></th>
        <th scope="col" class="text-center">
          <%= link_to "+", new_admin_book_path, class: "btn btn-success" %>
        </th>
      </tr>
    </thead>
    <tbody class="table-book">
      <%= render @books %>
    </tbody>
  </table>
  <%= paginate @books, theme: "twitter-bootstrap-3" %>
</div>

app/views/admin/books/index.js.erb
<% if @books.blank? %>
  $(".table-book").html("<tr class='text-center'><td colspan='6' style='color:silver'>"+I18n.t('no_record')+"</td></tr>")
<% else %>
  $(".table-book")
    .html(`<%= j render partial:"book", collection: @books, as: :book %>`)
<% end %>

app/views/admin/books/new.html.erb
<% provide :button_text, (t "books.create") %>
<center>
  <h1><%= t "book.add" %></h1>
</center>
<div class="col-md-8 col-md-offset-2">
  <%= render "form" %>
</div>