config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"

  root "static_pages#home"
  get "home", to: "static_pages#home"
  namespace :admin do
    resources :books
    resources :requests, only: %i(edit update index)
    resources :categories
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
  end

  resources :account_activations, only: [:edit]
  resources :books, only: %i(show) do 
    resources :ratings do
      resources :comments
    end
    resources :user_books
  end
  resources :mark_books, only: %i(index)
  resources :users do
    resources :member do
      get :following, :followers
    end
  end
  resources :requests
  resources :search_books, only: %i(index)
  resources :my_requests, only: %i(index)
  resources :search_users, only: %i(index)
  resources :likes, only: %i(create destroy)
  resources :category_books,only: %i(index)
  resources :time_lines, only: %i(index)
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/admin/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <%= link_to (t "layout.header.home"), root_path, class: "navbar-brand" %>
    </div>
    <ul class="nav navbar-nav">
      <% if is_admin? %>
        <li><%= link_to (t "layout.header.list_book"), admin_books_path %></li>
        <li> <%= link_to (t "layout.header.handler_request"), admin_requests_path %> </li>
        <li> <%= link_to (t "category.list_cat"), admin_categories_path %> </li>
      <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if logged_in? %>
        <li><p class="hi-user"><%= (t "users.user_mailer.hi") + ", " + current_user_admin.name %></p></li>
        <li> <%= link_to (t "layout.header.logout"), logout_path, method: :delete %> </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= render "layouts/rails_default" %>
  </head>
  <body>
    <%= render "layouts/admin/header" %>
    <div class="container">
      <% flash.each do |message_type, content_messages| %>
        <div class="alert alert-<%= message_type %>"><%= content_messages %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
  <div id="area-modal">
  </div>
</html>