config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"

  root "static_pages#home"
  get "home", to: "static_pages#home"
  namespace :admin do
    resources :books
    resources :requests, only: %i(edit update index)
    resources :categories
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
  end

  resources :account_activations, only: [:edit]
  resources :books, only: %i(show) do 
    resources :ratings do
      resources :comments
    end
    resources :user_books
  end
  resources :mark_books, only: %i(index)
  resources :users do
    resources :member do
      get :following, :followers
    end
  end
  resources :requests
  resources :search_books, only: %i(index)
  resources :my_requests, only: %i(index)
  resources :search_users, only: %i(index)
  resources :likes, only: %i(create destroy)
  resources :category_books,only: %i(index)
  resources :time_lines, only: %i(index)
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :relationships, only: [:create, :destroy]
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :book
  has_many :comments

  validates :title, presence: true
  validates :content, presence: true, length: {minimum: Settings.minimum_content_review}
  validates :poin, presence: true
  
  scope :by_book, -> (book_id){includes(:user).order(created_at: :asc)
    .where(book_id: book_id)}
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :load_book, only: %i(new create edit update)
  before_action :load_rating, only: %i(edit update)
  before_action :verify_login, only: %i(new create edit update)

  def new
    @rating = Rating.new
  end

  def create
    @rating = current_user.ratings.build rating_params
    @rating.book_id = params[:book_id]
    if @rating.save
      make_history @book, Settings.rating_book
      flash[:success] = t "review.create_success"
      redirect_to @book
    else
      render :new
    end
  end

  def edit; end

  def update
    if @rating.update_attributes rating_params
      flash[:success] = t "review.update_success"
      redirect_to @book
    else
      flash[:danger] = t "review.update_fail"
      render :edit
    end
  end

  private

  def load_rating
    @rating = Rating.find_by id: params[:id]
    render html: (t "rating.not_found_rating") if @rating.nil?
  end

  def load_book
    @book = Book.find_by id: params[:book_id]
    render html: (t "not_found") if @book.nil?
  end

  def rating_params
    params.require(:rating).permit :content, :poin, :title
  end
end

app/views/ratings/_form.html.erb
<div class="modal fade" id="modalRequest" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">
          <%= t "rating.form_rating" %>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </h5>
      </div>
      <div class="modal-body">
        <%= form_for [@book, @rating], remote: true do |f| %>
          <%= render "shared/error_messages", object: f.object %>
          <% if @rating.nil? %>
            <div class="form-group">
              <label><%= t "ratings.rating_this_book" %></label>
              <%= f.hidden_field :poin, class: "form-control" %>
              <div class="area-rate">
                <%= render "shared/rating_star" %>
              </div>
            </div>
          <% end %>
        
          <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title, class: "form-control" %>
          </div>
        
          <div class="form-group">
            <%= f.label :content %>
            <%= f.text_area :content, class: "form-control", rows: 15 %>
          </div>
          <center>
            <%= f.submit yield(:button_text), class: "btn btn-primary" %>
            <%= f.button "Cancel", class: "btn btn-danger" %> </br>
          </center>
        <% end %>
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>

app/views/ratings/_rating.html.erb
<hr>
<div class="row">
  <div class="col-md-1">
    <%= link_to (image_tag rating.user.avatar.thumb.url, class: "image-user-comment",
      title: rating.user.name).html_safe, rating.user %>
  </div>
  <div class="col-md-11">
    <div class="review-<%= rating.id %> review-rating">
    <div class="title-rating row">
      <div class="col-md-5">
        <%= rating.title %>
      </div>
    </div>
    <div class="row">
    <div class="col-md-2">
      <div class="area-view-rate">
        <%= render "ratings/star", poin: rating.poin %>
      </div>
    </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <%= rating.content %>
          <center class="area-btn-review">
            <%= link_to (t "rating.reply"), new_book_rating_comment_path(rating.book, rating), class: "btn btn-info btn-sm add_comment",
              remote: true, "data-review_id": rating.id %>
            <% if current_user.present? && current_user.id == rating.user_id %>
              <%= link_to (t "edit"), edit_book_rating_path(rating.book, rating), class: "btn btn-success btn-sm", remote: true %>
            <% end %>
          </center>
        <div id="comment-for-rating-<%= rating.id %>">
        </div>
        <div class="col-md-12" id="area-comment-rating-<%= rating.id %>">
          <%= render rating.comments.ordered %>
        </div>
      </div>
    </div>
    <br>
  </div>
  </div>
</div>

app/views/ratings/_star.html.erb
<div class="area-star">
  <span class="fa fa-star <%= 'checked' if poin >= 1 %>"></span>
  <span class="fa fa-star <%= 'checked' if poin >= 2 %>"></span>
  <span class="fa fa-star <%= 'checked' if poin >= 3 %>"></span>
  <span class="fa fa-star <%= 'checked' if poin >= 4 %>"></span>
  <span class="fa fa-star <%= 'checked' if poin >= 5 %>"></span>
</div>

app/views/ratings/destroy.js.erb
$(".delete-review").bind("ajax:success", function() {
   $(document).find(".review-"+$(this).data("review")).fadeOut()
});

app/views/ratings/edit.html.erb
<center>
  <h1><%= t "review.review" %></h1>
</center>
<div class="col-md-8">
  <%= form_for [@book, @rating] do |f| %>
    <%= render "shared/error_messages", object: f.object %>

    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :content %>
      <%= f.text_area :content, class: "form-control", rows: 20 %>
    </div>

    <%= f.submit (t "users.new.create"), class: "btn btn-primary" %> </br>
  <% end %>
</div>

app/views/ratings/edit.js.erb
$(".modal-backdrop").remove()
<% provide :button_text, (t "edit")%>
$('#area-modal').html(`<%= render "form" %>`)
$("#modalRequest").modal("toggle")
  

app/views/ratings/new.html.erb
<center>
  <h1><%= t "review.review" %></h1>
</center>
<div class="col-md-8">
  <%= render "form" %>
</div>
<div class="col-md-4">
  <div class="row">
    <div class="col-md-12">
      <%= image_tag @book.image.thumb.url %>
    </div>
    <div class="col-md-12">
      <h2 class="title-book-name"><%= @book.name %></h2>
      <h4><%= @book.author %></h4>
      <p><%= @book.description %></p>
    </div>
  </div>
</div>

app/views/ratings/update.js.erb
<% if @success %>
  toastr.success(I18n.t('update_success'))
<% else %>
  toastr.error(I18n.t('update_fail'))
<% end %>